---
title: "R Notebook"
output:
  html_document:
    toc: yes
    df_print: paged
  word_document:
    toc: yes
  pdf_document:
    toc: yes
---

This CSV is pulled from the Canvas CSV folder provided in the class. I have renamed this csv "universities_info". I hope this is acceptable.

```{r}
DF = read_csv("C:\\Users\\rspake1\\Desktop\\CSV files\\Universities_info.csv",TRUE) 

DF[is.na(DF)] <- 0

DF$Total_enrollment = (DF$`# new stud. enrolled`) + (DF$`# FT undergrad`) + (DF$`# PT undergrad`)

State_enrollment <- DF %>% group_by(State) %>% summarise(Total_enrollment)

Model_1 = lm(DF$`Graduation rate`~DF$`stud./fac. ratio`) %>% na.omit(DF)
summary(Model_1)

Model_2 = lm(DF$`Graduation rate`~DF$`Public (1)/ Private (2)`) %>% na.omit(DF)
summary(Model_2)

sapply(DF, mean, 2) %>% na.omit(DF)

hist(DF$Total_enrollment)

plot(Model_1)
```

The above Chunk reads the "Universities_info" csv from my computer, denoting it as "DF".
I then replace all N/A with "0".
Next, "Total_enrollment" is added to the data set for each university.
data frame "state_enrollment" sorts the "total_enrollment" by state  and combines them for each state.
Model_1 shows a regression model between graduation rates and student/faculty ratios.
A summary is provided of these statistics.
Model_2 illustrates a regression model between graduates rates and private vs. public schools.
A summary is provided of these statistics.
Sapply returns the means for each column in DF. 
A histogram is plotted, showing the frequency of total enrollment across all universities in the data.
Lastly, scatter plots are provided from the regression Model_1.